/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef workercontroller_CONSTANTS_H
#define workercontroller_CONSTANTS_H

#include "workercontroller_types.h"

namespace workercontroller {

class workercontrollerConstants {
 public:
  workercontrollerConstants();

};

extern const workercontrollerConstants g_workercontroller_constants;

} // namespace

#endif
