/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "workercontroller_constants.h"

namespace workercontroller {

const workercontrollerConstants g_workercontroller_constants;

workercontrollerConstants::workercontrollerConstants() {
}

} // namespace

